apiVersion: veecode.backstage.io/v1alpha1
kind: Cluster
metadata:
  name: "teste-new-template-spec"
  annotations:
    github.com/project-slug: veecode-homolog/teste-new-template-spec
    backstage.io/techdocs-ref: dir:.
  environment:
    cluster_type: ec2
    ingress_type: kong
    domain: teste-new-template-spec
    github.com/workflows: deploy.yml,destroy.yml
    cluster/instructions: |
      scp -i ./key-pair.pem ${EC2_USER}@${EC2_HOST}:/home/${EC2_USER}/.kube/config ~/.kube/config    
spec:
  type: ec2
  lifecycle: experimental
  owner: "group:default/admin"
